# Generated by Django 5.2.9 on 2026-02-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='no name', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
