# Generated by Django 5.2.9 on 2026-02-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
