# Generated by Django 5.2.9 on 2026-02-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=1000)),
                ("num_total_volunteers", models.IntegerField()),
                ("num_signed_volunteers", models.IntegerField()),
                ("distance_from_user_km", models.FloatField()),
            ],
        ),
    ]
