# Generated by Django 5.2.9 on 2026-02-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('numTotalVolunteers', models.IntegerField()),
                ('numSignedVolunteers', models.IntegerField()),
                ('distanceFromUserKilometers', models.FloatField()),
            ],
        ),
    ]
