# Generated by Django 5.2.9 on 2026-02-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_opportunity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='opportunities/'),
        ),
    ]
