# Generated by Django 5.2.9 on 2026-02-12 18:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_opportunity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
